### ISSUE TITLE
Testing: Extract Text

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ExtractText#1]
Test west feature and file format described in the [README](https://github.com/omeka-s-modules/ExtractText/blob/master/README.md).

**Comment by mebrett** [comment]
Are all of these extractors installed/available on the dev server?

**Comment by mebrett** [comment]
When trying to do docx files, I get the error `Error validating "Reference.docx". Cannot store files with the media type "application/vnd.openxmlformats-officedocument.wordprocessingml.document".`  Note that this happens whether or not Extract Text is active.

**Comment by mebrett** [comment]
As a note, multiple files' text for a single item all go into the same instance of the extracted property. I don't know how many people will be uploading multiple files to a single item, and nothing gets overwritten at least.

**Comment by jimsafley** [comment]
>Are all of these extractors installed/available on the dev server?

In the module's configuration page you should see a table that shows which extractors are available in the dev server.

>As a note, multiple files' text for a single item all go into the same instance of the extracted property. 

It's a fundamental constraint of the module that an item's "extracted text" property will contain the aggregated text of its child media, in order.

**Comment by mebrett** [comment]
It makes sense to me that it would all end up in one place. Wanted to be sure that this was expected behavior (and that it removed only one if you deleted the media, which it does)

**Comment by mebrett** [comment]
So far I've been able to successfully test everything expect docx (as mentioned above) and html. For html files, I get the following errors: `Error validating "Bohemia.html". Cannot store files with the media type "text/html".` and `Error validating "Bohemia.html". Cannot store files with the resolved extension "html".`

**Comment by zerocrates** [comment]
You can add the type and extension to the whitelists under S's global settings to allow HTML... I'm not sure we'd want to make a change allowing HTML by default though.

**Comment by mebrett** [comment]
Works for HTML if the type is `text/html`

Dev server does not have docx2txt so I couldn't test docx files
