### ISSUE TITLE
Testing: Extract XML

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ExtractText#11]
The [xml-extract](https://github.com/omeka-s-modules/ExtractText/compare/master...xml-extract) branch enables text extraction from XML files. To test this upload an XML file as media. The text of the XML file (not the tags) should automatically be added as an "extracted text" value.

**Comment by allanaaa** [comment]
This works well. You have to manually add XML to your allowed media types and file extensions - is there any way for the module update to do that automatically? If not, I'll pop it in the docs and you can mention it in the readme.

**Comment by jimsafley** [comment]
Given the security concerns, I'd rather that we document that users must add XML to the allowed types/extensions themselves.
