### ISSUE TITLE
docx2txt doesn't appear to be available

### ISSUE THREAD

**Issue by Becklighter** [omeka-s-modules/ExtractText#4]
docx2txt is installed on my omeka-s server.
When I browse to “Administration -> Modules -> Extract Text -> Configure” I see this:
![image](https://user-images.githubusercontent.com/16211791/60538249-77921c80-9cc7-11e9-92fd-81c391f65913.png)

But on the same server, if I execute the command "docx2txt test.docx -" I see the content of the document, demonstrating that it is installed.

**Comment by jimsafley** [comment]
The module detects the existence of a command using [command](http://manpages.ubuntu.com/manpages/bionic/en/man1/command.1posix.html). What happens when you enter `command -v docx2txt` in your terminal?

**Comment by Becklighter** [comment]
input: command -v docx2txt
output: /usr/bin/docx2txt

Thanks for getting back to me.

**Comment by jimsafley** [comment]
Since it outputs a path the module should mark docx2txt as available. Perhaps your webserver doesn't have permission to execute the docx2txt binary?

**Comment by Becklighter** [comment]
Thanks, you were right.  SE Linux was getting in the way.
