### ISSUE TITLE
"extracted text" should be "Extracted Text"

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/ExtractText#9]
The vocab label of the extracttext:extracted_text property should be capitalized for appearance on public pages:

<img width="347" alt="Screenshot 2023-12-11 at 13 21 59" src="https://github.com/omeka-s-modules/ExtractText/assets/28012148/04674f56-c253-49d8-aa25-17e0de37e29b">

Dublin Core does it in Camel Case (Date Issued, Alternative Title). I suppose we should match that. 
I realize you can rename it in every single resource template but it'd be nice not to have to.

**Comment by jimsafley** [comment]
The capitalization for a label is immaterial beyond personal preference. There are many RDF vocabularies that do not capitalize their labels (e.g. BIBO, FOAF, SKOS). For sure it's not optimal for people who want capitalization, but this is why we have alternate labels.
